### ISSUE TITLE
[BUG] Object Limit

### ISSUE THREAD

**Issue by MaeDaGoof** [OldTimes-Software/jaded#20]
Adding too many objects to a level seems to give this error.  At least it seems to be an Object limit issue
![image_2023-05-30_050942113](https://github.com/OldTimes-Software/jaded/assets/99543861/64a34b42-fd57-4a33-b551-7d0d97a53eaf)

**Comment by hogsy** [comment]
Upper limits for flags and nodes has been removed, technically solving this problem. Need to investigate code a bit more, though, as need to downsize safely as elements are removed prior to clean up. Once this is done, will look at doing the same for objects.

**Comment by hogsy** [comment]
Bumped up object limits, rather than removing it entirely for now. There are other changes I've made which will make migrating away from hard limits easier in future, but I think the change introduced should resolve this problem regardless.
