### ISSUE TITLE
[BUG] Export World to MAD Memory Error

### ISSUE THREAD

**Issue by MaeDaGoof** [OldTimes-Software/jaded#27]
Using both old and regular 'Export World to Mad' gives this error,  simply saying 'No More Memory'. 
![image](https://github.com/OldTimes-Software/jaded/assets/99543861/6e1ba430-551d-4cfb-abb1-ab0ec82dac33)
After this, even loading up the engine or a world will give the same error if done in the same instance of the editor.
After pressing ok, it simply gives an exception message for debugging. 
Nothing is shown in the log related to it.

**Comment by hogsy** [comment]
I know I keep asking, but can you *please* use the templates?

And yes, I'm aware of the issue, it was mentioned in the notes for the upcoming version and will be resolved in the release that follows, whenever I eventually release it.

**Comment by MaeDaGoof** [comment]
Ah, sorry, i will do it from now on

**Comment by hogsy** [comment]
Fixed!
