### ISSUE TITLE
[BUG] Broken Fur Effect

### ISSUE THREAD

**Issue by ShowinGrowin** [OldTimes-Software/jaded#28]
## Summary
It appears that the fur/hair effect is a bit broken on the newest version of jaded. I've tried an older build from April that appears to not have this issue. This bug seems to not only effect the creation of new materials with this effect but also permanently breaks old materials the moment they're opened in the editor. 

On a more minor note, some materials display incorrectly such as the purple hookable rings seen in world 2. They're grey in the editor though I'm not sure if it's always been this way.

## Steps to Reproduce
Open an existing material that uses the effect. In this case Rayman's grandma hair. (RayCust_Cheveux03)

## Expected Result
It opens up and maintains the fur effect while letting the user edit it. (this also goes for creating a new material with the fur effect)

## Actual Result
The fur/hair effect is completely removed and can't be re-added in any way from what I can tell. Checking the fur checkbox doesn't have any immediate visual changes in the viewport and saving it doesn't actually save the fur check. It will always remain unchecked. (this wasn't the case in the original editor from what I've tested)

## Screenshots or Videos
https://cdn.discordapp.com/attachments/1068601467755319336/1124979080245288970/image.png (BEFORE OPENING THE MATERIAL)
https://cdn.discordapp.com/attachments/1068601467755319336/1124979125204025506/image.png (AFTER OPENING THE MATERIAL)

**Comment by hogsy** [comment]
Fixed! Flag was getting cleared by some stupid asshole. Will try and get the new build to you asap, but need to finish some other changes first.
