### ISSUE TITLE
Remove Shape Errors

### ISSUE THREAD

**Issue by ShowinGrowin** [OldTimes-Software/jaded#30]
## Summary
Certain rigged model imports cause jade to spam errors in the console. I haven't exactly been able to figure out why but the game itself has no issues actually using these models despite this. The log causing lag is the only real problem.

## Screenshots or Videos
![modelerror](https://github.com/OldTimes-Software/jaded/assets/43835376/4142cd3e-55d5-4ad5-9480-ce930fb72f6a)

**Comment by hogsy** [comment]
Not going to remove them because it's still probably worth fixing at some point, but I've done a bodge so that the warning only shows once per object instead.
